#!/usr/bin/env python3
import urllib.request
import base64
import datetime


username = "your@email.com"
password_base64 = "your.base64.encoded.password="
domain = "mydomain.noip.com"
target_ip = "" # If it's different from your current public IP

password = base64.b64decode(password_base64).decode("utf-8")
target_ip_query = "" if not target_ip else f"&myip={target_ip}"

password_mgr = urllib.request.HTTPPasswordMgrWithDefaultRealm()

top_level_url = f"https://dynupdate.no-ip.com/nic/update?hostname={domain}{target_ip_query}"

password_mgr.add_password(None, top_level_url, username, password)

handler = urllib.request.HTTPBasicAuthHandler(password_mgr)

opener = urllib.request.build_opener(handler)

resp = opener.open(top_level_url)

response_str = resp.read().decode("utf-8").strip()

now = datetime.datetime.now()
print(f"{now}: {response_str}")
